<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pig-Sikap Digital Sales Receipt</title>
</head>
<body style="font-family: Arial, sans-serif; color: #1f2937; line-height: 1.5;">
    <h2 style="color: #0c6d57; margin-bottom: 8px;">Pig-Sikap Digital Sales Receipt</h2>
    <p>Hello {{ $sale->buyer?->name ?? 'Buyer' }},</p>
    <p>
        Attached is your digital sales receipt from {{ $associationName }}.
        Please keep this copy for your records.
    </p>
    <p>
        <strong>Receipt Number:</strong> {{ $sale->digital_receipt_number }}<br>
        <strong>Sale Date:</strong> {{ $sale->sale_date?->format('M d, Y') }}<br>
        <strong>Total Amount:</strong> PHP {{ number_format((float) $sale->amount, 2) }}
    </p>
    <p>Thank you.</p>
    <p style="font-size: 12px; color: #6b7280;">
        This receipt was generated by Pig-Sikap for transparency and verification.
    </p>
</body>
</html>
