<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sales Receipt {{ $sale->digital_receipt_number }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #1f2937; font-size: 12px; }
        .header { border-bottom: 2px solid #0c6d57; padding-bottom: 8px; margin-bottom: 12px; }
        .title { font-size: 18px; font-weight: bold; color: #0c6d57; }
        .section-title { margin-top: 12px; font-weight: bold; color: #0c6d57; }
        table { width: 100%; border-collapse: collapse; margin-top: 6px; }
        th, td { padding: 6px 4px; border-bottom: 1px solid #e5e7eb; text-align: left; }
        .right { text-align: right; }
        .muted { color: #6b7280; }
        .footer { margin-top: 20px; font-size: 10px; color: #4b5563; border-top: 1px solid #e5e7eb; padding-top: 8px; }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">Digital Sales Receipt</div>
        <div>{{ $associationName }}</div>
        <div class="muted">Receipt #{{ $sale->digital_receipt_number }}</div>
    </div>

    <div class="section-title">Buyer Information</div>
    <table>
        <tr><th>Buyer Name</th><td>{{ $sale->buyer?->name ?? 'N/A' }}</td></tr>
        <tr><th>Buyer Email</th><td>{{ $sale->buyer?->email ?? $sale->digital_receipt_email ?? 'N/A' }}</td></tr>
        <tr><th>Contact Number</th><td>{{ $sale->buyer?->contact_number ?? 'N/A' }}</td></tr>
        <tr><th>Address</th><td>{{ $sale->buyer?->address ?? 'N/A' }}</td></tr>
    </table>

    <div class="section-title">Sale Details</div>
    <table>
        <tr><th>Batch/Cycle</th><td>{{ $sale->cycle?->batch_code ?? 'N/A' }}</td></tr>
        <tr><th>Sale Date</th><td>{{ $sale->sale_date?->format('M d, Y') }}</td></tr>
        <tr><th>Sale Method</th><td>{{ $sale->sale_method === 'live_weight' ? 'Live Weight' : 'Per Head' }}</td></tr>
        <tr><th>Pigs Sold</th><td>{{ $sale->pigs_sold }}</td></tr>
        @if ($sale->sale_method === 'live_weight')
            <tr><th>Live Weight</th><td>{{ number_format((float) $sale->live_weight_kg, 2) }} kg</td></tr>
            <tr><th>Price per kg</th><td>&#8369;{{ number_format((float) $sale->price_per_kg, 2) }}</td></tr>
        @else
            <tr><th>Price per head</th><td>&#8369;{{ number_format((float) $sale->price_per_head, 2) }}</td></tr>
        @endif
    </table>

    <div class="section-title">Payment Summary</div>
    <table>
        <tr><th>Total Amount</th><td class="right">&#8369;{{ number_format((float) $sale->amount, 2) }}</td></tr>
        <tr><th>Amount Paid</th><td class="right">&#8369;{{ number_format((float) $sale->amount_paid, 2) }}</td></tr>
        <tr><th>Balance</th><td class="right">&#8369;{{ number_format(max((float) $sale->amount - (float) $sale->amount_paid, 0), 2) }}</td></tr>
        <tr><th>Payment Status</th><td>{{ ucfirst((string) $sale->payment_status) }}</td></tr>
    </table>

    <div class="section-title">Other Details</div>
    <table>
        <tr><th>Recorded By</th><td>{{ $sale->createdBy?->name ?? 'N/A' }}</td></tr>
        <tr><th>Receipt Reference</th><td>{{ $sale->receipt_reference ?? 'N/A' }}</td></tr>
        <tr><th>Notes</th><td>{{ $sale->notes ?? 'N/A' }}</td></tr>
    </table>

    <div class="footer">
        This receipt was generated by Pig-Sikap for transparency and verification. Generated {{ $generatedAt->format('M d, Y h:i A') }}.
    </div>
</body>
</html>
