@php
$hasCycle = !empty($cycleName);
$hasExtra = !empty($extraMeta);
@endphp

<div class="rounded-xl border border-gray-200 bg-gray-50 p-4">
    <h4 class="mb-3 text-xs font-bold uppercase tracking-wider text-gray-400">Report Info</h4>
    <dl class="grid gap-2 text-sm sm:grid-cols-2 lg:grid-cols-3">
        <div>
            <dt class="text-xs font-semibold text-gray-500">Generated By</dt>
            <dd class="font-medium text-gray-900">{{ $preparedBy ?? auth()->user()?->name ?? 'System' }}</dd>
        </div>
        <div>
            <dt class="text-xs font-semibold text-gray-500">Date Generated</dt>
            <dd class="font-medium text-gray-900">{{ ($generatedAt ?? now())->format('M d, Y h:i A') }}</dd>
        </div>
        @if ($hasCycle)
        <div>
            <dt class="text-xs font-semibold text-gray-500">Cycle</dt>
            <dd class="font-medium text-gray-900">{{ $cycleName }}</dd>
        </div>
        @endif
        <div>
            <dt class="text-xs font-semibold text-gray-500">Period / Filter</dt>
            <dd class="font-medium text-gray-900">{{ $periodDisplay ?? ($filters['date_range'] ?? 'All data') }}</dd>
        </div>
        @if ($hasExtra)
            @foreach ($extraMeta as $label => $value)
            <div>
                <dt class="text-xs font-semibold text-gray-500">{{ $label }}</dt>
                <dd class="font-medium text-gray-900">{{ $value }}</dd>
            </div>
            @endforeach
        @endif
    </dl>
</div>
